# Generated by Django 3.2 on 2021-05-10 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Regisration',
        ),
    ]
