# Generated by Django 3.2 on 2021-05-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='imgupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='uploads')),
            ],
        ),
        migrations.DeleteModel(
            name='userprofile',
        ),
    ]
