# Generated by Django 3.2 on 2021-05-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_orderfood_tablebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='rest_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
