# Generated by Django 3.2 on 2021-05-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_uprofile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprofile',
            name='profileimg',
            field=models.ImageField(default='profileimgs\\defaultpimg.jpg', upload_to='profileimgs/'),
        ),
    ]
