# Generated by Django 3.2 on 2021-05-19 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0014_alter_uprofile_profileimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dbtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testfield1', models.CharField(max_length=255)),
                ('testfield2', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='roombooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(blank=True, max_length=255)),
                ('roomno', models.IntegerField()),
                ('date_in', models.DateField()),
                ('date_out', models.DateField()),
                ('uname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
