# Generated by Django 3.2 on 2022-04-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_dbtest_roombooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dbtest',
        ),
    ]
